name: Deploy to S3

on: 
  push:
    branches:    
      - master    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: clone code from repo
        uses: actions/checkout@v1

      - name: install nodejs v10
        uses: actions/setup-node@v1
      
      - name: npm install, build
        run: |
          npm ci
          npm run build --if-present
          ls -la
          
      - name: push static site to build branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: public
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"
