name: Deploy to S3

on: 
  push:
    branches:    
      - master    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: clone code from repo
        uses: actions/checkout@v1

      - name: install nodejs v10
        uses: actions/setup-node@v1

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
      
      - name: npm install, build
        run: |
          npm ci
          npm run build --if-present
          ls -la

      - name: deploy static site to S3 bucket
        run: >-
          aws s3 sync ./public/ s3://${{ secrets.AWS_S3_BUCKET }} --delete